BMNC/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import apps_user.urls as apps_user
import apps_login.urls as apps_login
import apps_public.urls as apps_public
import apps_polling.urls as apps_polling

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(apps_login, namespace='apps-login')),
    url(r'^news/', include(apps_public, namespace='apps-public')),
    url(r'^polling/', include(apps_polling, namespace='apps-polling')),
    url(r'^user/', include(apps_user, namespace='apps-user')),
    url(r'^$', RedirectView.as_view(permanent=True, url='news/'), name='index'),
]

apps_public/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', news_page, name='news-page'),
    url(r'^detail/$', news_detail, name='news-detail'),
    url(r'^submit/$', createNews, name='create-News'),
   # url(r'^cek-url/$', cek_url, name='cek-url'),
]

apps_public/models.py
from django.db import models
from apps_login.models import *

from datetime import datetime

# Create your models here.

class Berita(models.Model):
    url = models.CharField(primary_key=True, max_length=50)
    judul = models.CharField(max_length=100)
    topik = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=datetime.now)
    updated_at = models.DateTimeField(default=datetime.now)
    jumlah_kata = models.IntegerField()
    rerata_rating = models.FloatField(default = 5)
    id_universitas = models.ForeignKey('apps_login.Universitas', models.DO_NOTHING, db_column='id_universitas')
    id_berita = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'berita'

class NarasumberBerita(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    id_narasumber = models.ForeignKey(Narasumber, models.DO_NOTHING, db_column='id_narasumber')

    class Meta:
        managed = False
        db_table = 'narasumber_berita'
        unique_together = (('url_berita', 'id_narasumber'),)


class Tag(models.Model):
    url_berita = models.ForeignKey(Berita, models.DO_NOTHING, db_column='url_berita', primary_key=True)
    tag = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'tag'
        unique_together = (('url_berita', 'tag'),)

apps_public/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .form import *
from django.db import connection
from django.contrib import messages
from datetime import datetime

# Create your views here.
response={}

def news_page(request):
    response['news_page'] = "Disini halaman home/news"
    response ['form_berita'] = BeritaForm
    news = Berita.objects.all()
    response['news'] = news

    return render(request, 'news_page.html', response)

def news_detail(request):
    response['detail_news'] = "Disini halaman detail news berisi komentar dll"
    return render(request, 'news_detail.html', response)

@csrf_exempt
def createNews(request):
    form = BeritaForm(data=request.POST)
    cursor = connection.cursor()

    if (request.method == 'POST' and form.is_valid()):
        cursor = connection.cursor()
        query = ('select count(*) from Berita')
        cursor.execute(query)
        count = cursor.fetchone()[0] #(2,)
      
        id_berita = 0
        if count > 0:
            id_berita = count + 1
        else:
            id_berita = 1

        Judul = request.POST.get('Judul', False)
        Url = "http://bmnc_news.com/news-" + str(id_berita)
        Topik = request.POST.get('Topik', False)
        JumlahKata= request.POST.get('JumlahKata', False)
        Tag = request.POST.get('Tag', False)
        narasumber_id = request.session['id']
        waktu = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        query = 'select id_universitas from narasumber where id = ' + str(narasumber_id) 
        count = cursor.execute (query)
        id_univ = cursor.fetchone()[0]
        
        query = ("insert into berita (url, judul, topik, jumlah_kata, id_universitas, id_berita, created_at, updated_at, rerata_rating) values ('" 
            + str(Url) + "','" + str(Judul) + "','" +str(Topik) +"'," + str(JumlahKata) + "," + str(id_univ) +"," + str(id_berita) + ",'" 
            + str(waktu)+ "','" + str(waktu) +"'," + str(0) + ");")
        cursor.execute(query)

        tagg = Tag.replace(" ", "")
        tags = tagg.split(",")
        for i in range (0,len(tags)):
            print (str(tags[i]))
            query = "insert into tag (url_berita, tag) values('" + str(Url) + "','" + str(tags[i]) + "');"
            cursor.execute(query)
        
        query = "insert into Narasumber_Berita (url_berita, id_narasumber) values ('" + str(Url) + "'," + str(narasumber_id) + ");"
        cursor.execute(query)

        messages.success(request, "News Posted!")
        return HttpResponseRedirect(reverse('apps-public:news-page'))
    else :
    	return HttpResponse("null")

apps_public/templates/news_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
News Detail - BMNC
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/detail_berita.css' %}">
{% endblock %}

{% block content %}
<div class="all-content">
	<div class="container">
		<div class="temp">
			<div class="title-div">
				<h3>Detail Berita</h3>
			</div>
			<div class="reg-form">
			</div>
		</div>
	</div>
</div>
{% endblock %}

apps_public/templates/news_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
Home - BMNC
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main_page.css' %}">
{% endblock %}

{% block content %}
<div class="all-content">
	<div class="container">
		<div class="temp">
			<div class="title-div">
				<div class="row">
					<div class="col-sm-9">
						<h3>Hot Topics</h3>
					</div>
	          		<div class="col-sm-3 text-right">
	          			<!-- Trigger the modal with a button -->
						<!--<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal">Add News</button>-->
						{% if request.session.is_login == "login" %}
						<button class="button button4" data-toggle="modal" data-target="#myModal"><span>Create News</span></button>
						{% endif %}
						<!-- Modal -->
						<div id="myModal" class="modal fade" role="dialog">
							<div class="modal-dialog">

							    <!-- Modal content-->
							    <form method="POST" action="{% url 'apps-public:create-News' %}">
							    	{% csrf_token %}
							    
							    <div class="modal-content">
							    	<div class="modal-header mod-header">
								        <button type="button" class="close" data-dismiss="modal">&times;</button>
								        <h4 class="modal-title">Wazzup Lambe?</h4>
								    </div>
								    <div class="modal-body mod-body">
								    	<div class="form-group" >
								    		<label for = "{{ form_berita.Judul_for_label}}">{{form_berita.Judul.label}}</label>
                  							{{form_berita.Judul}}		                					
								      	</div>
								      	
								      	<!--div class="form-group">
								      		<label for = "{{ form_berita.Url_for_label}}">{{form_berita.Url.label}}</label>
                  							{{form_berita.Url}}
                  							<div class = "notif">
                  								  <small>Url has been taken, please insert other urls</small>
                  							</div>        						
								      	</div-->
								      	<div class="form-group">
								      		<label for = "{{ form_berita.Topik_for_label}}">{{form_berita.Topik.label}}</label>
                  							{{form_berita.Topik}}		    		                					
								      	</div>
								      	<div class="form-group">
								      		<label for = "{{ form_berita.JumlahKata_for_label}}">{{form_berita.JumlahKata.label}}</label>
                  							{{form_berita.JumlahKata}}
		                  				
		                					
								      	</div>
								      	<div class="form-group">
								      		<label for = "{{ form_berita.Tag_for_label}}">{{form_berita.Tag.label}}</label>
                  							
								      		<p style="text-align:left"><small>Enter the tags and saparate with commas<small></p>
		                  					{{form_berita.Tag}}
		                  					
		                				</div>
		                				<hr class="style14" style="opacity:0.1">
		                				<input type="submit" value="submit" class="btn btn-block btn-lg btn-default">
								    </div>
								    <div class="modal-footer">
								    	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
								    </div>
								</div>
							</form>

							</div>
						</div>
	          		</div>
	          	</div>
	        </div>
        	<div class="reg-form">
				<div class="row">
					<div class="col-sm-8">
						{% if news %}
                        	{% for berita in news %}
								<a href="/news/detail/"><div class="panel panel-default news-box">
									<div class="panel-body">
										<div class="row">
											<div class="col-sm-4">
												<img src=https://image.ibb.co/eBitgc/pexels_photo_635705.jpg class="img-news" height="150" width="230">
											</div>
											<div class="col-sm-8">
												<h4><b>{{berita.judul}}</b></h4>
												<h5><small> Posted on {{berita.created_at}}</small></h5>
											</div>
										</div>
									</div>
								</div>
								</a>
							{% endfor %}
                        {% else %}
                        <div class="alert alert-danger text-center">
                        <strong>Oops!</strong> No data yet.
                        </div>
                        {% endif %}

						<!--
						<div class="panel panel-default news-box">
							<div class="panel-body">
								<div class="row">
									<div class="col-sm-4">
										<img src=https://image.ibb.co/eBitgc/pexels_photo_635705.jpg class="img-news" height="150" width="230">
									</div>
									<div class="col-sm-8">
										<h4><b>[Upcoming] I’m Sayantan Das, managing director of Foodpanda Malaysia. Ask me anything!</b></h4>
										<h5><small> Posted on June 6 2018 </small></h5>
									</div>
								</div>
							</div>
						</div>
						<div class="panel panel-default news-box">
							<div class="panel-body">
								<div class="row">
									<div class="col-sm-4">
										<img src=https://image.ibb.co/eBitgc/pexels_photo_635705.jpg class="img-news" height="150" width="230">
									</div>
									<div class="col-sm-8">
										<h4><b>[Upcoming] I’m Sayantan Das, managing director of Foodpanda Malaysia. Ask me anything!</b></h4>
										<h5><small> Posted on June 6 2018 </small></h5>
									</div>
								</div>
							</div>
						</div>-->

					</div>
					<div id="news-bar" class="col-sm-4">
						<!--<div class="panel panel-default pad">
							<div class="panel-heading">All News</div>
							<div class="panel-body sizing">
								<div class="list-group">
									<a href="#" class="list-group-item">Asia news roundup: Xiaomi finally files for IPO, Amazon makes Flipkart offer, and more</a>
									<a href="#" class="list-group-item">[Upcoming] I’m Sayantan Das, managing director of Foodpanda Malaysia. Ask me anything!</a>
									<a href="#" class="list-group-item">Third item</a>
								</div>
							</div>
						</div>-->
							<div class="news-title">
	                    		<h3 style="color: #575C5D"><b>All News</b></h3>
	                    	</div>
		                    <div class="list-news">
		                    	<div class="list-group">
		                    		{% if news %}
                        				{% for berita in news %}
		                    				<a href="#" class="list-group-item">{{berita.judul}}</a>
		                    			{% endfor %}
			                        {% else %}
				                        <div class="alert alert-danger text-center">
				                        <strong>Oops!</strong> No data yet.
				                        </div>
			                        {% endif %}
		                    	</div>
		                    </div>
					</div>
				</div>
			</div>
		</div>
	</div>
 <!-- <h1>This is news/home page</h1>
  <h2>{{news_page}}</h2>-->
</div>


{% endblock %}