BMNC/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import apps_user.urls as apps_user
import apps_login.urls as apps_login
import apps_public.urls as apps_public
import apps_polling.urls as apps_polling

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(apps_login, namespace='apps-login')),
    url(r'^news/', include(apps_public, namespace='apps-public')),
    url(r'^polling/', include(apps_polling, namespace='apps-polling')),
    url(r'^user/', include(apps_user, namespace='apps-user')),
    url(r'^$', RedirectView.as_view(permanent=True, url='news/'), name='index'),
]

apps_polling/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', polling_page, name='polling-page'),
    url(r'^submit/$', createNewsPolling, name='create-NewsPolling'),
    url(r'^submits/$', createPolling, name='create-Polling'),
]

apps_polling/models.py
from django.db import models


class Polling(models.Model):
    id = models.IntegerField(primary_key=True)
    polling_start = models.DateTimeField()
    polling_end = models.DateTimeField()
    total_responden = models.IntegerField(default = 0)

    class Meta:
        managed = False
        db_table = 'polling'


class PollingBerita(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    url_berita = models.ForeignKey('apps_public.Berita', models.DO_NOTHING, db_column='url_berita')
       

    class Meta:
        managed = False
        db_table = 'polling_berita'


class PollingBiasa(models.Model):
    id_polling = models.ForeignKey(Polling, models.DO_NOTHING, db_column='id_polling', primary_key=True)
    url = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'polling_biasa'

apps_polling/views.py
from django.shortcuts import render, redirect, reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import *
from .form import *
from apps_public.models import *
from django.db import connection
from django.contrib import messages
from apps_login.models import *
from apps_public.models import *
from .models import *


response = {}

def polling_page(request):
    response ['polling_berita_form'] = PollingBeritaForm
    response ['PollingForm'] = PollingForm
    cursor = connection.cursor()
    query = 'select id_polling, judul, polling_start, polling_end , total_responden from polling, polling_berita, berita where id_polling = id and url_berita = url'
    cursor.execute(query)
    pol_news = cursor.fetchall()
    response['pol_news'] = pol_news

    cursor = connection.cursor()
    query = 'select id_polling, deskripsi, url, polling_start, polling_end , total_responden from polling, polling_biasa where id_polling = id'
    cursor.execute(query)
    pol_reg = cursor.fetchall()
    response['pol_reg'] = pol_reg

    return render(request, 'polling_page.html', response)


    


@csrf_exempt
def createNewsPolling(request):
    form = PollingBeritaForm(data=request.POST)

    if (request.method == 'POST' and form.is_valid()):
        cursor = connection.cursor()
        query = ('select count(*) from Polling')
        cursor.execute(query)
        count = cursor.fetchone()[0] #(2,)

        id_polling = 0
        if count > 0:
            id_polling = count + 1
        else:
            id_polling = 1

        url_berita= request.POST.get('Urlberita', False)#request.POST.get['username']
        start_date = request.POST.get('Startdate', False)
        end_date = request.POST.get('EndDate', False)
        questions = request.POST.get('Questions', False)
        answers = request.POST.get('Answers', False)

        #insert new polling
        query = ("insert into Polling (id, polling_start, polling_end, total_responden) values (" + str(id_polling) + ",'"
            + str(start_date) + "','" + str(end_date) + "'," + str(0) + ");" )
        cursor.execute(query)

        #insert new polling berita
        query = "insert into Polling_berita (id_polling, url_berita) values (" + str(id_polling) + ",'" + str(url_berita) +"');"
        cursor.execute(query)

        messages.success(request, "News Polling Submitted!")
        return HttpResponseRedirect(reverse('apps-polling:polling-page'))
    else :
    	return HttpResponse("null")


@csrf_exempt
def createPolling(request):
    form = PollingForm(data=request.POST)

    if (request.method == 'POST' and form.is_valid()):
        cursor = connection.cursor()
        cursor.execute('select count(*) from Polling')
        count = cursor.fetchone()[0] #(2,)

        id_polling = 0
        if count > 0:
            id_polling = count + 1
        else:
            id_polling = 1

        descriptions = request.POST.get('Deskripsi', False)#request.POST.get['username']
        url = request.POST.get('Url', False)
        start_date = request.POST.get('Startdate', False)
        end_date = request.POST.get('EndDate', False)
        questions = request.POST.get('Questions', False)
        answers = request.POST.get('Answers', False)

        # insert new polling
        query = ("insert into Polling (id, polling_start, polling_end, total_responden) values (" + str(id_polling) + ",'"
            + str(start_date) + "','" + str(end_date) + "'," + str(0) + ");" )
        cursor.execute(query)

       	#insert new polling biasa
        query = ("insert into polling_biasa (id_polling, url, deskripsi) values (" + str(id_polling) + ",'" + str(url) + "','"
            + str(descriptions) +"');")
       	cursor.execute(query)

        messages.success(request, "Polling Submitted!")
        return HttpResponseRedirect(reverse('apps-polling:polling-page'))
    else :
    	return HttpResponse("null")

apps_polling/templates/polling_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
Polling - BMNC
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/polling_page1.css' %}">
{% endblock %}


{% block content %}

<div class="all-content">
  <div class="container">
    <div class="row">
        <div class="title-div">
        	<div class="row">
        		<div class="col-sm-6 text-left">
        			 <h3>Show Polling</h3>
        		</div>
        		<div class="col-sm-6 text-right">
               {% if request.session.is_login == 'login' %}
        			 <button class="button button4" data-toggle="modal" data-target="#news-polling"><span>Create News-Polling</span></button>
         			 <button class="button button4" data-toggle="modal" data-target="#polling" ><span>Create Polling</span></button>
               {% else %}
               {% endif %}
        		</div>
        	</div>
        </div>
          <div class="bg-box">
            <div class="row" style="padding: 30px 3px">
            <div class="col-sm-12">
              <div class="row">
                <div class="panel-group">
                  <div class="col-sm-4 col-sm-offset-2">
                    <div class="panel panel-danger">
                      <div class="panel-heading">List News-Polling</div>
                      <div class="panel-body">

                        {% if pol_news %}
                          {% for pol in pol_news %}
                            <a href="#" class="list-group-item" data-toggle="modal" data-target="#detail-poll{{pol.0}}">{{pol.1}}</a>

                             <!-- Modal -->
                             <div id="detail-poll{{pol.0}}" class="modal fade" role="dialog">
                               <div class="modal-dialog">

                               <!-- Modal content-->
                               <div class="modal-content">
                                 <div class="modal-header mod-header">
                                   <button type="button" class="close" data-dismiss="modal">&times;</button>
                                   <h4 class="modal-title" style="color:white">Polling</h4>
                                 </div>
                                 <div class="modal-body">
                                   <div class="row">
                                      <div class="col-sm-6">
                                        <div class="tanggal">
                                            <span style="font-size: 12px">Start Date</span><button type="button" class="btn-block btn btn-back btn-xs">{{pol.2}}</button>
                                            <br>
                                            <span style="font-size: 12px">End Date</span><button type="button" class="btn-block btn btn-back btn-xs">{{pol.3}}</button>
                                        </div>
                                      </div>
                                      <div class="col-sm-6">
                                        <h3><b>Total Responden</b></h3>
                                        <h2><span class="glyphicon glyphicon-user"></span>   {{pol.4}}</h2>
                                      </div>
                                    </div>
                                 </div>
                               </div>
                             </div>
                           </div>
                          {% endfor %}
                        {% else %}
                        <div class="alert alert-danger text-center">
                        <strong>Oops!</strong> No data yet.
                        </div>
                        {% endif %}

                      </div><!--panel body-->
                    </div><!--panel-->
                  </div><!--col-->
                <!--</div>panel group-->

                  <div class="col-sm-4 panel-satunya">
                    <div class="panel panel-danger ">
                      <div class="panel-heading ">List Polling</div>
                      <div class="panel-body">
                        {% if pol_reg %}
                          {% for poll in pol_reg %}
                            <a href="#" class="list-group-item" data-toggle="modal" data-target="#detail-poll-reg{{poll.0}}">{{poll.1}}</a>

                            <div id="detail-poll-reg{{poll.0}}" class="modal fade" role="dialog">
                              <div class="modal-dialog">

                                <!-- Modal content-->
                                <div class="modal-content">
                                  <div class="modal-header mod-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title" style="color:white">Polling</h4>
                                  </div>
                                  <div class="modal-body">
                                    <h2><b>{{poll.1}}</b></h2>
                                    <div class="url">{{poll.2}}</div>
                                    <br>
                                    <br>
                                    <div class="row">
                                      <div class="col-sm-6">
                                        <div class="tanggal">
                                            <span style="font-size: 12px">Start Date</span><button type="button" class="btn-block btn btn-back btn-xs">{{poll.3}}</button>
                                            <br>
                                            <span style="font-size: 12px">End Date</span><button type="button" class="btn-block btn btn-back btn-xs">{{poll.4}}</button>
                                        </div>
                                      </div>
                                      <div class="col-sm-6">
                                        <h3><b>Total Responden</b></h3>
                                        <h2><span class="glyphicon glyphicon-user"></span>   {{poll.id_polling.5}}</h2>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          {% endfor %}
                        {% else %}
                        <div class="alert alert-danger text-center">
                        <strong>Oops!</strong> No data yet.
                        </div>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>






     <!-- Modal -->
  <div id="news-polling" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create News Polling</h4>
        </div>
        <div class="modal-body">
          <div class="text-center">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIoDcV8hm2L7rB0AQzesX_VpKzxScSVImnhTa7fhFj6HIv9r27w" style="width:120px" class="img-circle">
          </div>
          <form method="POST" action="{% url 'apps-polling:create-NewsPolling' %}">
            {% csrf_token %}
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <label for = "{{ polling_berita_form.Urlberita_for_label}}">{{polling_berita_form.Urlberita.label}}</label>
                  {{polling_berita_form.Urlberita}}
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for = "{{ polling_berita_form.Startdate_for_label}}">{{polling_berita_form.Startdate.label}}</label>
                      {{polling_berita_form.Startdate}}
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for = "{{ polling_berita_form.EndDate_for_label}}">{{polling_berita_form.EndDate.label}}</label>
                      {{polling_berita_form.EndDate}}
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label for = "{{ polling_berita_form.Questions_for_label}}">{{polling_berita_form.Questions.label}}</label>
                  {{polling_berita_form.Questions}}
                </div>
                <div class="form-group">
                  <label for = "{{ polling_berita_form.Answers_for_label}}">{{polling_berita_form.Answers.label}}</label>
                  <p style="text-align:left"><small>Enter the options and saparate with commas. ex. Option1, Option2, etc.</small></p>
                  {{polling_berita_form.Answers}}
                </div>
              </div>
            </div>
            <div class="text-right">
              <input type="submit" value="submit" class="btn btn-block btn-lg btn-default">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>


  <!-- Modal untuk polling biasa -->
  <div id="polling" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create Polling</h4>
        </div>
        <div class="modal-body">
          <div class="text-center">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHIoDcV8hm2L7rB0AQzesX_VpKzxScSVImnhTa7fhFj6HIv9r27w" style="width:120px" class="img-circle">
          </div>
          <form method="POST" action="{% url 'apps-polling:create-Polling' %}">
          {% csrf_token %}
            <div class="row">
              <div class="col-sm-12">
                <div class="form-group">
                  <label for = "{{ PollingForm.Deskripsi_for_label}}">{{PollingForm.Deskripsi.label}}</label>
                  {{PollingForm.Deskripsi}}
                  <label for = "{{ PollingForm.Url_for_label}}">{{PollingForm.Url.label}}</label>
                  {{PollingForm.Url}}
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for = "{{ PollingForm.Startdate_for_label}}">{{PollingForm.Startdate.label}}</label>
                      {{PollingForm.Startdate}}
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="form-group">
                      <label for = "{{ PollingForm.EndDate_for_label}}">{{PollingForm.EndDate.label}}</label>
                      {{PollingForm.EndDate}}
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label for = "{{ PollingForm.Questions_for_label}}">{{PollingForm.Questions.label}}</label>
                  {{PollingForm.Questions}}
                </div>
                <div class="form-group">
                  <label for = "{{ PollingForm.Answers_for_label}}">{{PollingForm.Answers.label}}</label>
                  <p style="text-align:left"><small>You can input answers up to 5 answers. But leave it empty for least than 5 answers.</small></p>
                  {{PollingForm.Answers}}
                </div>
              </div>
            </div>
            <div class="text-right">
              <input type="submit" value="submits" class="btn btn-block btn-lg btn-default">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}